WIP Migrate from CircleCI 1.0 to 2.0
flyve-mdm/flyve-mdm-ios pull request #144
Opened 2018-06-22 17:29 UTC by hectorerb

Signed-off-by: Hector Rondon <hrondon@teclib.com>

### Changes description

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@hectorerb |2|

### References

Closes #135 
Related #N/A
Depends on #N/A

2018-06-24 19:33 UTC, ajsb85 requested changes

2018-06-24 19:33 UTC, ajsb85 commented on ci/scripts/set_locate.sh
> +#   Copyright © 2017 Teclib. All rights reserved.
2017-2018

2018-06-24 19:33 UTC, ajsb85 commented on ci/scripts/set_locate.sh
> +# @author    Hector Rondon
Email

2018-06-24 19:33 UTC, ajsb85 commented on ci/scripts/set_locate.sh
> +# @link      https://github.com/flyve-mdm/flyve-mdm-ios-agent
New repo URL

2018-06-25 21:03 UTC, hectorerb commented on ci/scripts/set_locate.sh
> +#   Copyright © 2017 Teclib. All rights reserved.
done

2018-06-25 21:03 UTC, hectorerb commented on ci/scripts/set_locate.sh
> +# @author    Hector Rondon
Done

2018-06-25 21:03 UTC, hectorerb commented on ci/scripts/set_locate.sh
> +# @link      https://github.com/flyve-mdm/flyve-mdm-ios-agent
Done

2018-06-25 21:04 UTC, ajsb85 approved these changes

2018-06-25 21:09 UTC, merged